apiVersion: v1
kind: Service
metadata:
  name: guestbook
  namespace: bar
  labels:
    app: guestbook
spec:
  ports:
  - port: 8081
    targetPort: 80
    nodePort: 30007
  type: NodePort
  selector:
    app: guestbook
